name: PreventBlockFall
author: Tioplaya
version: '${project.version}'
main: ru.tioplaya.PreventBlockFall
api-version: '1.14'
commands:
  PreventBlockFall:
    aliases: [ pbf, pbfall ]
    usage: "Usage: /pbf [reload]"
    description: main command
